disabled_rules: # rule identifiers to exclude from linting
  - trailing_whitespace
  - line_length
opt_in_rules: # some rules are only opt-in
  - empty_count
included: # paths to include during linting. `""` means all files.
  - .
excluded: # paths to ignore during linting
  - Pods
